version: 2.1
orbs:
    node: circleci/node@2.1.0
jobs:
    Deploy:
        environment:
            OBRAZ: wojciechwrobel22/ask_circleci
      
        docker:
            - image: circleci/buildpack-deps:stretch
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Build docker image
                command: cd server && docker build -t $OBRAZ:serverwwrobel .
            - run:
                name: Build docker image
                command: cd client && docker build -t $OBRAZ:clientwwrobel .
                
            - run:
                name: Publish docker image to docker hub
                command: |
                    echo "$PASSWORD" | docker login -u "$MY_LOGIN" --password-stdin
                    docker push $OBRAZ:serverwwrobel           
            - run:
                name: Publish docker image to docker hub
                command: |
                    echo "$PASSWORD" | docker login -u "$MY_LOGIN" --password-stdin
                    docker push $OBRAZ:clientwwrobel
              
    BuildTestClient:
        executor: 
            name: node/default
        steps:  
            - checkout
            - run: cd client && npm install
            - run: cd client && npm test
    BuildTestServer:
        executor: 
            name: node/default
        steps:  
            - checkout
            - run: cd server && npm install
            - run: cd server && npm test      
workflows:

    BuildTest:
        jobs:
            - BuildTestServer:
                filters:
                    branches:
                        only: master
                        
                        
            - BuildTestClient:
                filters:
                    branches:
                        only: master
            
            - Deploy: 
                requires: 
                    - BuildTestClient
                    - BuildTestServer
